title:                   Jean Couteau
subtitle:
content_is_about:        # maybe! used in footer menu title
show_logo:               hide # 'show' or 'hide'
description:             "Historian, anthropologist, art critic Jean Couteau writes about Bali life, connecting reality and myth, delivering clean, meaningful insights to understand social dynamics." # max 160 digits
keywords:                Bali, culture, social dynamics, understanding, reality and myth, insights, ethnology, history, anthropology
language:                en
version:                 0.1.4
sass:
  style:                 compressed

baseurl:                 ""
url:                     "https://jean.junglestar.org"
qr_to_website:           # put qr in footer
menu:                    # 'has_menu' or empty

company:
  name:                  Jean Couteau
  legal_name:            Jean Couteau #overrides 'company.name' in footer
  country:               Indonesia

#SEO https://jekyll.github.io/jekyll-seo-tag/usage/
#
# SEO tag will use the YAML front matter if included in a post, page, or document:
#
# title
# description
# image - (e.g., /assets/page-pic.jpg)
# author - Page-specific author (see below)
# lang - Page-specific language

author:                  Jean Couteau
twitter:
  username:              jcouteaubali
facebook:
  app_id:                #Facebook app ID for Facebook insights
  publisher:             #Facebook page URL or ID of the publishing entity
  admins:                #Facebook user ID for domain insights linked to a personal account
logo:                    /assets/favicons/apple-touch-icon-152x152.png
webmaster_verifications:
  google:                google32e66f1a5601ec40


google:
  analytics:             G-RHL5S3PJE0

# Build settings
markdown:                kramdown
plugins:
 - jekyll/tagging
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-sitemap
 - html-proofer
exclude:
  - Gemfile.lock
  - node_modules
  - package-lock.json
  - Gemfile
  - 2DO.md
  - README.md

permalink:               /:title/ # pretty

tag_page_layout:         post_index_tag
tag_page_dir:            ./
tag_permalink_style:     pretty
ignored_tags:

defaults:
  - scope:
      path:              ""
    values:
      layout:            article # change this to get the layout needed
      image:             /assets/p/default.jpg
