title:                   Jean Couteau
subtitle:
content_is_about:        # maybe! used in footer menu title
show_logo:               hide # 'show' or 'hide'
description:             "Historian and art critic Jean Couteau brings us stories depicting the life on Bali, sometimes real, sometimes myth, always meaningful. " # max 160 digits
keywords:
language:                en
version:                 0.0.6
sass:
  style:                 compressed

baseurl:                 ""
url:                     "https://jean.junglestar.com"
qr_to_website:           # put qr in footer
menu:                    # 'has_menu' or empty

company:
  name:                  Jean Couteau
  legal_name:            Jean Couteau #overrides 'company.name' in footer
  country:               Indonesia


#SEO https://jekyll.github.io/jekyll-seo-tag/usage/
#
# SEO tag will use the YAML front matter if included in a post, page, or document:
#
# title
# description
# image - (e.g., /assets/page-pic.jpg)
# author - Page-specific author (see below)
# lang - Page-specific language

author:                  rokma
twitter:
  username:              rokmatwit
facebook:
  app_id:                #Facebook app ID for Facebook insights
  publisher:             #Facebook page URL or ID of the publishing entity
  admins:                #Facebook user ID for domain insights linked to a personal account
logo:                    /assets/favicons/apple-touch-icon-152x152.png
webmaster_verifications:
  google:                google32e66f1a5601ec40


google:
  analytics:             G-RHL5S3PJE0

# Build settings
markdown:                kramdown
plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-sitemap
 - html-proofer
exclude:
  - Gemfile.lock
  - node_modules
  - package-lock.json
  - Gemfile
  - 2DO.md
  - README.md

permalink:               /:title/ # pretty

collections:
  articles:
    output:              true
    permalink:           /:title/

defaults:
  - scope:
      path:              ""
      type:              "articles"
    values:
      layout:            "article"
  - scope:
      path:              ""
    values:
      layout:            default # change this to get the layout needed
